/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'displayName' : IDL.Text,
  'coins' : IDL.Nat,
});
export const PlayerStatusView = IDL.Record({
  'hasSeenCards' : IDL.Bool,
  'hasPacked' : IDL.Bool,
  'hasPlayedTurn' : IDL.Bool,
});
export const Player = IDL.Record({
  'principal' : IDL.Principal,
  'displayName' : IDL.Text,
  'coins' : IDL.Nat,
});
export const TableView = IDL.Record({
  'id' : IDL.Nat,
  'isGameActive' : IDL.Bool,
  'playerStatuses' : IDL.Vec(PlayerStatusView),
  'currentTurn' : IDL.Nat,
  'players' : IDL.Vec(Player),
  'currentBet' : IDL.Nat,
  'currentPot' : IDL.Nat,
  'lastActionTime' : IDL.Int,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGameSettings' : IDL.Func(
      [],
      [IDL.Record({ 'inactivityTimeout' : IDL.Nat, 'bootAmount' : IDL.Nat })],
      ['query'],
    ),
  'getQueueSize' : IDL.Func([], [IDL.Nat], ['query']),
  'getTable' : IDL.Func([], [IDL.Opt(TableView)], []),
  'getTables' : IDL.Func([], [IDL.Vec(TableView)], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'joinQueue' : IDL.Func([], [], []),
  'performAction' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateGameSettings' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'displayName' : IDL.Text,
    'coins' : IDL.Nat,
  });
  const PlayerStatusView = IDL.Record({
    'hasSeenCards' : IDL.Bool,
    'hasPacked' : IDL.Bool,
    'hasPlayedTurn' : IDL.Bool,
  });
  const Player = IDL.Record({
    'principal' : IDL.Principal,
    'displayName' : IDL.Text,
    'coins' : IDL.Nat,
  });
  const TableView = IDL.Record({
    'id' : IDL.Nat,
    'isGameActive' : IDL.Bool,
    'playerStatuses' : IDL.Vec(PlayerStatusView),
    'currentTurn' : IDL.Nat,
    'players' : IDL.Vec(Player),
    'currentBet' : IDL.Nat,
    'currentPot' : IDL.Nat,
    'lastActionTime' : IDL.Int,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGameSettings' : IDL.Func(
        [],
        [IDL.Record({ 'inactivityTimeout' : IDL.Nat, 'bootAmount' : IDL.Nat })],
        ['query'],
      ),
    'getQueueSize' : IDL.Func([], [IDL.Nat], ['query']),
    'getTable' : IDL.Func([], [IDL.Opt(TableView)], []),
    'getTables' : IDL.Func([], [IDL.Vec(TableView)], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'joinQueue' : IDL.Func([], [], []),
    'performAction' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateGameSettings' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };