/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Player {
  'principal' : Principal,
  'displayName' : string,
  'coins' : bigint,
}
export interface PlayerStatusView {
  'hasSeenCards' : boolean,
  'hasPacked' : boolean,
  'hasPlayedTurn' : boolean,
}
export interface TableView {
  'id' : bigint,
  'isGameActive' : boolean,
  'playerStatuses' : Array<PlayerStatusView>,
  'currentTurn' : bigint,
  'players' : Array<Player>,
  'currentBet' : bigint,
  'currentPot' : bigint,
  'lastActionTime' : bigint,
}
export interface UserProfile { 'displayName' : string, 'coins' : bigint }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGameSettings' : ActorMethod<
    [],
    { 'inactivityTimeout' : bigint, 'bootAmount' : bigint }
  >,
  'getQueueSize' : ActorMethod<[], bigint>,
  'getTable' : ActorMethod<[], [] | [TableView]>,
  'getTables' : ActorMethod<[], Array<TableView>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'joinQueue' : ActorMethod<[], undefined>,
  'performAction' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateGameSettings' : ActorMethod<[bigint, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];